# Generated by Django 4.2.21 on 2025-05-22 20:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_customuser_core_custom_cuit_e40e19_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='core_custom_role_77f64b_idx'),
        ),
    ]
